spring.application.name=book-service
server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5555/mcr_book
spring.datasource.username=rascal
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show.sql=true
spring.jpa.properties.hibernate.format.sql=true

# Paging
spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=100

# Redis
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.enable=false
