spring.application.name=auth-service
server.port=8082
server.address=0.0.0.0

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5555/mcr_user
spring.datasource.username=rascal
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show.sql=true
spring.jpa.properties.hibernate.format.sql=true

# Paging
spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=100

# Admin data
admin.username=rascal
admin.email=admin@gmail.com
admin.password=atmin123
